mysql:
    host: "104.196.37.201"
    userName: "root"
    password: "M9KoGocA"
    database: "dungeonrealms"
    port: 3306
redis:
    password: "password"
    host: "localhost"
    port: 6379
    preventTimeout: true